# Generated by Django 4.1.3 on 2022-12-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=51)),
                ("text", models.TextField(max_length=361)),
            ],
        ),
    ]
