# Generated by Django 4.1.3 on 2022-12-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("original_name", models.CharField(max_length=255)),
                ("extension", models.CharField(max_length=16)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
