# Generated by Django 4.1.3 on 2022-12-21 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_storefile_delete_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefile",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
